version: '3.0'
services:
  python:
    container_name: user-anomaly-detection
    build: ./
    ports:
      - 8000:80
    volumes:
      - ./src:/app
      - ./assets:/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY